### PR TITLE
#16: Several stat framework improvements / fixes

### LINKED ISSUE #16: Add StatisticManager.queryStatistic(name, type, since)

### PR DESCRIPTION
**Pull request by mathieucarbou**
➕ Close #16 - Stat framework improvements and fixes

- ➕ StatisticManager.getSampledStatistic()
- ➕ StatisticManager.getSampledCompoundStatistic()
- ➕ SampledStatistic.history(since)
- ➕ SampledStatistic.type()
- ➕ RegisteredStatistic.getType()
- ➕ RegisteredCompoundStatistic.getResult()
- ➕ RegisteredRatioStatistic.getSampledStatistic()
- 🐛 Fix generic signatures in methods
- 🎨 Moved the stat mapper classes from Ehcache

This is for ehcache/ehcache3#1579 : to cleanup some duplicated code

### CODE REVIEW

File: src/test/java/org/terracotta/statistics/StatisticMapperTest.java [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+import static org.terracotta.statistics.StatisticMapperTest.Source.E;
+import static org.terracotta.statistics.StatisticMapperTest.Target.A;
+import static org.terracotta.statistics.StatisticMapperTest.Target.B;
+
+public class StatisticMapperTest {
+
+  @Test
+  public void testInvalidSourceStatisticSet() {
+    try {
+      new StatisticMapper<Source, Target>(Collections.<Target, Set<Source>>singletonMap(A, of(C, D)), null);
```
Comment (mathieucarbou) [inline src/test/java/org/terracotta/statistics/StatisticMapperTest.java]: Ahah! This code has just been moved from ehcache to there. So issues that were there are still there because it has not been touched. See https://goo.gl/NbQCle.

I'll have a look at them ;-) I think there have been some miss in a previous ehcache PR review then!

**Comment by mathieucarbou** [comment]
@lorban : changes done!
